logging:
  pattern:
    dateformat: dd MMM yyyy HH:mm:ss

spring:
  application:
    name: clear-ledger-server
  jackson:
    serialization:
      write-dates-as-timestamps: false
  web:
    locale: zh_CN

mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/repository/**/*.xml
