openapi: 3.1.0
info:
  title: Clear Ledger - Ledger APIs
  description: Ledger APIs
  version: 1.0.0
components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
security: [ ]
servers:
  - url: http://localhost:8080
paths:
  /ledgers:
    get:
      summary: Get joined ledgers
      description: Get joined ledgers
      responses:
        200:
          description: A list of ledgers retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: The unique identifier of the ledger
                    name:
                      type: string
                      description: The name of the ledger
                    description:
                      type: string
                      description: A brief description of the ledger
                    role:
                      type: string
                      enum:
                        - owner
                        - member
                      description: The user's role in this ledger
                    joinedAt:
                      type: string
                      format: date-time
                      description: The date and time when the user joined the ledger
                  required:
                    - id
                    - name
                    - role
                    - joinedAt
                examples:
                  - id: "1"
                    name: "Sample Ledger"
                    description: null
                    role: "member"
                    joinedAt: "2025-03-25T14:33:22"
    post:
      summary: Create a new ledger
      description: Create a new ledger
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Ledger name
                description:
                  type: string
                  description: Ledger description
      responses:
        200:
          description: A list of ledgers retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The unique identifier of the ledger
                  name:
                    type: string
                    description: The name of the ledger
                  description:
                    type: string
                    description: A brief description of the ledger
                  role:
                    type: string
                    enum:
                      - owner
                      - member
                    description: The user's role in this ledger
                  joinedAt:
                    type: string
                    format: date-time
                    description: The date and time when the user joined the ledger
                required:
                  - id
                  - name
                  - role
                  - joinedAt
        409:
          description: Ledger creation failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  timestamp:
                    type: string
                    format: date-time
                    description: Request time
                  message:
                    type: string
                    description: Error message
    patch:
      summary: Update ledger information
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: Ledger's ID
                name:
                  type: string
                  description: The name of this ledger
                description:
                  type: string
                  description: A brief description of this ledger
              required:
                - id
      responses:
        202:
          description: Ledger has been updated successfully
        400:
          description: Missing required properties
        403:
          description: This operation is forbidden to current user
        409:
          description: The name has been taken